[package]
name = "orbotkeys"
version = "0.1.0"
edition = "2021"

[lib]
name = "orbotkeys"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
x25519-dalek = "1"
base32 = "0.3.1"
jni = { version = "0.13.1", default-features = false }
rand_core = "0.5.1"